devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: Alsa
    channels: 2
    device: plughw:Loopback,1,0
    format: S16LE
  playback:
    type: Alsa
    channels: 2
    device: plughw:CARD=sndrpihifiberry,DEV=0
    format: S32LE
filters:
  bass:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 100
      slope: 6
      gain: 0
  mid:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1000
      q: 0.7
      gain: 0
  high:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 5000
      slope: 6
      gain: 0
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: 0
            inverted: false
  mono:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false
pipeline:
  - type: Mixer
    name: mono
  - type: Filter
    channel: 0
    names:
      - bass
      - mid
      - high
  - type: Filter
    channel: 1
    names:
      - bass
      - mid
      - high
